name: Production Deployment

on:
  push:
    branches:
      - main

env:
  NPM_CONFIG_LEGACY_PEER_DEPS: true
  NODE_ENV: production
  GATSBY_WEB3_API_URL: https://api.web3forms.com/submit
  GATSBY_WEB3_API_KEY: ${{ secrets.GATSBY_WEB3_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: enriikke/gatsby-gh-pages-action@v2.2.1
        with:
          access-token: ${{ secrets.REPO_ACCESS_TOKEN }}
          deploy-branch: deploy
          skip-publish: false