name: Pull Request Validation

on:
  pull_request:
    branches:
      - main

env:
  NPM_CONFIG_LEGACY_PEER_DEPS: true

jobs:
  build:
    name: Pull Request Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: enriikke/gatsby-gh-pages-action@v2.2.1
        with:
          access-token: ${{ secrets.REPO_ACCESS_TOKEN }}
          deploy-branch: deploy
          skip-publish: true